service: devlogHandlers

package:
  artifact: dist/artifacts.zip

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  region: ap-northeast-2
  versionFunctions: false
  apiGateway:
    disableDefaultEndpoint: true
  iam:
    role: ${env:AWS_ROLE_ARN}

functions:
  imageDestinationGenerator:
    handler: index.imageDestinationGenerator
    name: devlog-imageDestinationGenerator
    description: Image destination generator
    memorySize: 1024
    timeout: 5
    events:
      - http:
          path: destinations/images
          method: post
    environment:
      AWS_S3_REGION: ${env:AWS_S3_REGION}
      AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}
      S3_BUCKET_KEY_PREFIX: ${env:S3_BUCKET_KEY_PREFIX}
      BACKEND_HOST: ${env:BACKEND_HOST}
      BACKEND_PATH_PREFIX: ${env:BACKEND_PATH_PREFIX}
  imageHandler:
    handler: index.imageHandler
    name: devlog-imageHandler
    description: Image handler
    memorySize: 2048
    timeout: 10
    environment:
      BACKEND_HOST: ${env:BACKEND_HOST}
      BACKEND_PATH_PREFIX: ${env:BACKEND_PATH_PREFIX}
      CDN_URL_PREFIX: ${env:CDN_URL_PREFIX}
  thumbnailDestinationGenerator:
    handler: index.thumbnailDestinationGenerator
    name: devlog-thumbnailDestinationGenerator
    description: Thumbnail destination generator
    memorySize: 1024
    timeout: 5
    events:
      - http:
          path: destinations/thumbnails
          method: post
    environment:
      AWS_S3_REGION: ${env:AWS_S3_REGION}
      AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}
      S3_BUCKET_KEY_PREFIX: ${env:S3_BUCKET_KEY_PREFIX}
      BACKEND_HOST: ${env:BACKEND_HOST}
      BACKEND_PATH_PREFIX: ${env:BACKEND_PATH_PREFIX}
  thumbnailHandler:
    handler: index.thumbnailHandler
    name: devlog-thumbnailHandler
    description: Thumbnail handler
    memorySize: 2048
    timeout: 10
    environment:
      BACKEND_HOST: ${env:BACKEND_HOST}
      BACKEND_PATH_PREFIX: ${env:BACKEND_PATH_PREFIX}
      CDN_URL_PREFIX: ${env:CDN_URL_PREFIX}
  uploadEventHandler:
    handler: index.uploadEventHandler
    name: devlog-uploadEventHandler
    description: Upload event handler
    memorySize: 1024
    timeout: 20
    events:
      - s3:
          existing: true
          bucket: ${env:AWS_S3_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${env:S3_BUCKET_KEY_PREFIX}
    environment:
      AWS_LAMBDA_REGION: ${env:AWS_LAMBDA_REGION}
      IMAGE_HANDLER_NAME: ${env:IMAGE_HANDLER_NAME}
      THUMBNAIL_HANDLER_NAME: ${env:THUMBNAIL_HANDLER_NAME}

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${env:DOMAIN}
    basePath: 'v1'
    createRoute53Record: false

useDotenv: true

configValidationMode: error
unresolvedVariablesNotificationMode: error
